export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const SET_SITE_SETTINGS_DATA = 'SET_SITE_SETTINGS_DATA';
export const SET_LOGGEDIN_USER_DATA = 'SET_LOGGEDIN_USER_DATA';
export const SET_LOGGEDIN_CREDIT_DATA = 'SET_LOGGEDIN_CREDIT_DATA';
export const SET_USER_DOWNLOADED_CV_DATA = 'SET_USER_DOWNLOADED_CV_DATA';
